### ISSUE TITLE
Allow for adding labels

### ISSUE THREAD

**Issue by Iristyle** [puppetlabs/tlser#6]
To be able to properly flush the secret resource using a label-based filter, there needs to be a way to specify that metadata

In particular, I'm interested in adding `app.kubernetes.io/part-of: cd4pe`

**Comment by MikaelSmith** [comment]
The simplest solution for this is to add a repeatable argument to add multiple labels, like
```
-l label1=value -l app.kubernetes.io/part-of=cd4pe
```

I believe this format is reasonable given the [constraints on label syntax](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) and that this mirrors how label filters are specified.

----

A more complex use-case might use https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/ to inject the tlser pod's annotations and labels as files in the pod, and tlser could apply those to any secrets it creates. While this is an interesting idea, I'm not going to address it for this issue.

**Comment by MikaelSmith** [comment]
Can base repeatable arguments on https://stackoverflow.com/a/28323276.
